import { UserProvider, getSession } from '@auth0/nextjs-auth0/client';
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getSession();
  return (
    <html lang="en">
      <UserProvider user={session?.user}>
        <body className={inter.className}>{children}</body>
      </UserProvider>
    </html>
  );
}
