
import { UserProvider } from '@auth0/nextjs-auth0/client';
import Head from 'next/head';
import NavBar from '../app/components/admin/layout/navbar/Navbar';
import '../app/globals.css';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children, metadata }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body>
        <UserProvider>
          <NavBar />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
